<a href="https://colab.research.google.com/github/Bishesh-P/Movie-Recommender-System/blob/main/Movie_Recommender_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [50]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/tmdb_5000_credits.csv')

In [51]:
#After the merge
movies.shape

(4803, 20)

In [52]:
credits.shape

(4803, 4)

In [53]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [54]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [55]:
movies = movies.merge(credits, on='title')

In [56]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [57]:
# genres
# id
# keywords
#overview
#title
#cast
#crew

movies = movies[['id', 'title', 'overview','keywords','genres','cast','crew']]

In [58]:
movies.head(1)

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [59]:
import ast

In [60]:
def convert(value):
  l = []
  for i in ast.literal_eval(value):
    l.append(i['name'])
  return l

In [61]:
movies['keywords'] = movies['keywords'].apply(convert)

In [62]:
movies.head(1)

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [63]:
movies['genres'] = movies['genres'].apply(convert)

In [64]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [65]:
def convert3(value):
  l = []
  count = 0
  for i in ast.literal_eval(value):
    if count != 3:
      l.append(i['name'])
      count +=1
    else:
      break
  return l

In [66]:
movies['cast'] = movies['cast'].apply(convert3)

In [67]:
movies['cast'][1]

['Johnny Depp', 'Orlando Bloom', 'Keira Knightley']

In [68]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [69]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [70]:
movies['crew']= movies['crew'].apply(fetch_director)

In [71]:
movies.head(1)

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [72]:
movies.sample(5)

,id,title,overview,keywords,genres,cast,crew
3078,1640,Crash,Los Angeles citizens with vastly separate live...,"[race politics, daughter, installer, police, f...",[Drama],"[Sandra Bullock, Don Cheadle, Matt Dillon]",[Paul Haggis]
3628,21014,Keeping Up with the Steins,All hilarity breaks loose in this heartwarming...,"[bar mitvah, party, independent film]",[Comedy],"[Daryl Sabara, Jami Gertz, Jeremy Piven]",[Scott Marshall]
2227,171274,Inherent Vice,"In Los Angeles at the turn of the 1970s, drug-...","[based on novel, 1970s, private investigator, ...","[Comedy, Romance, Crime, Drama, Mystery]","[Joaquin Phoenix, Josh Brolin, Owen Wilson]",[Paul Thomas Anderson]
993,9923,Domino,"The daughter of actor, Laurence Harvey turns a...","[bounty hunter, fbi, weapon, spectacle]","[Action, Crime]","[Keira Knightley, Mickey Rourke, Edgar Ramírez]",[Tony Scott]
450,9574,Flubber,"Professor Phillip Brainard, an absent minded p...","[wedding vows, inventor, slime, green, flight,...","[Comedy, Family, Science Fiction]","[Robin Williams, Marcia Gay Harden, Christophe...",[Les Mayfield]

In [74]:
movies.isnull().sum()

id          0
title       0
overview    3
keywords    0
genres      0
cast        0
crew        0
dtype: int64

In [79]:
movies.dropna(inplace = True)

In [82]:
def collapse(text):
  l = []
  for i in text:
    l.append(i.replace(" ", ""))
  return l

In [83]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [84]:
movies.sample(5)

,id,title,overview,keywords,genres,cast,crew
3361,308639,Dope,Malcolm is carefully surviving life in a tough...,"[california, hip-hop, harvarduniversity, geek,...","[Crime, Drama, Comedy]","[ShameikMoore, KierseyClemons, TonyRevolori]",[RickFamuyiwa]
2708,87729,Jefferson in Paris,"His wife having recently died, Thomas Jefferso...","[france, revolution, biography, president, his...","[Drama, Romance]","[NickNolte, GretaScacchi, ThandieNewton]",[JamesIvory]
264,8489,Ali,"In 1964, a brash new pro boxer, fresh from his...","[usa, transporter, boxer, biography, muhammad]",[Drama],"[WillSmith, JamieFoxx, JonVoight]",[MichaelMann]
1869,10030,Good Luck Chuck,"Cursed since childhood, dentist Charlie Kagan ...","[sex, aquarium, nudity, one-nightstand, bride,...","[Comedy, Drama, Romance]","[DaneCook, JessicaAlba, DanFogler]",[MarkHelfrich]
524,6538,Charlie Wilson's War,The true story of Texas congressman Charlie Wi...,"[washingtond.c., alcohol, cia, helicopter, ref...","[Comedy, Drama, History]","[TomHanks, PhilipSeymourHoffman, JuliaRoberts]",[MikeNichols]

In [85]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [86]:
movies.head()

,id,title,overview,keywords,genres,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [87]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [88]:
movies.head()

,id,title,overview,keywords,genres,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [89]:
movies = movies[['id','title','tags']]

In [90]:
movies.head()

,id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [91]:
movies['tags'] = movies['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_2251/2975052693.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['tags'].apply(lambda x:" ".join(x))

In [92]:
movies.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [93]:
from sklearn.feature_extraction.text import CountVectorizer

In [94]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [95]:
vectors = cv.fit_transform(movies['tags']).toarray()

In [96]:
movies.head()

,id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [98]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [100]:
from sklearn.metrics.pairwise import cosine_similarity

In [101]:
similarity = cosine_similarity(vectors)

In [104]:
similarity

array([[1.        , 0.08858079, 0.05905386, ..., 0.02478408, 0.02599376,
        0.        ],
       [0.08858079, 1.        , 0.06451613, ..., 0.02707652, 0.        ,
        0.        ],
       [0.05905386, 0.06451613, 1.        , ..., 0.02707652, 0.        ,
        0.        ],
       ...,
       [0.02478408, 0.02707652, 0.02707652, ..., 1.        , 0.07150969,
        0.0489116 ],
       [0.02599376, 0.        , 0.        , ..., 0.07150969, 1.        ,
        0.05129892],
       [0.        , 0.        , 0.        , ..., 0.0489116 , 0.05129892,
        1.        ]])

In [103]:
similarity.shape

(4806, 4806)

In [109]:
movies[movies['title'] == 'Avatar'].index[0]

np.int64(0)

In [113]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])

[(0, np.float64(1.0)),
 (539, np.float64(0.2537477434955704)),
 (1192, np.float64(0.25112360116696136)),
 (260, np.float64(0.2442250043490654)),
 (1214, np.float64(0.24260844762468367)),
 (507, np.float64(0.24165612634006073)),
 (582, np.float64(0.2372894989381248)),
 (1440, np.float64(0.2372894989381248)),
 (1202, np.float64(0.2369241569216954)),
 (1916, np.float64(0.23394386020951635)),
 (3728, np.float64(0.2324952774876386)),
 (74, np.float64(0.22305671869347438)),
 (322, np.float64(0.21919864974047634)),
 (3606, np.float64(0.21775177815467112)),
 (83, np.float64(0.21582051197002577)),
 (4190, np.float64(0.2152488010002526)),
 (2329, np.float64(0.2113701265354594)),
 (2405, np.float64(0.21059925059706255)),
 (47, np.float64(0.21049133398705727)),
 (61, np.float64(0.21029989116983447)),
 (495, np.float64(0.21029989116983447)),
 (972, np.float64(0.2101050788156825)),
 (2969, np.float64(0.2071841649822589)),
 (942, np.float64(0.20668850837512243)),
 (1327, np.float64(0.2056773510573183)),
 (466, np.float64(0.20567735105731827)),
 (2200, np.float64(0.20032733246124987)),
 (973, np.float64(0.1973593560521103)),
 (1199, np.float64(0.19727878476642874)),
 (151, np.float64(0.19374606457303215)),
 (1273, np.float64(0.19344776406574832)),
 (4046, np.float64(0.1926263261127128)),
 (3160, np.float64(0.18983159915049982)),
 (4405, np.float64(0.18983159915049982)),
 (2782, np.float64(0.1898315991504998)),
 (461, np.float64(0.18857857160117855)),
 (305, np.float64(0.18790823039834775)),
 (1533, np.float64(0.18668326147193276)),
 (931, np.float64(0.18641092980036)),
 (150, np.float64(0.18494886071852695)),
 (3536, np.float64(0.18427434427242972)),
 (1319, np.float64(0.18380365552345193)),
 (3325, np.float64(0.18380365552345193)),
 (27, np.float64(0.1823843010350213)),
 (2997, np.float64(0.1823843010350213)),
 (300, np.float64(0.18195633571851272)),
 (220, np.float64(0.18009006755629928)),
 (1069, np.float64(0.1797236580870839)),
 (36, np.float64(0.17972365808708385)),
 (4, np.float64(0.17757120130114434)),
 (184, np.float64(0.17757120130114434)),
 (67, np.float64(0.1771615786072478)),
 (301, np.float64(0.17684493567566834)),
 (373, np.float64(0.1752499093081954)),
 (46, np.float64(0.17170914210964275)),
 (7, np.float64(0.17155007848855516)),
 (2492, np.float64(0.17139779254776524)),
 (2727, np.float64(0.17139779254776524)),
 (1827, np.float64(0.1696751579473019)),
 (1342, np.float64(0.16916516233038026)),
 (149, np.float64(0.16702953813186466)),
 (26, np.float64(0.16673100431301852)),
 (1804, np.float64(0.16673100431301852)),
 (661, np.float64(0.16569860426698665)),
 (108, np.float64(0.1643989873053573)),
 (208, np.float64(0.1643989873053573)),
 (838, np.float64(0.1643989873053573)),
 (4008, np.float64(0.1643989873053573)),
 (94, np.float64(0.16120647005479025)),
 (581, np.float64(0.16120647005479025)),
 (2511, np.float64(0.16120647005479025)),
 (52, np.float64(0.1600142241187995)),
 (1392, np.float64(0.15958626340564364)),
 (31, np.float64(0.15819299929208316)),
 (1295, np.float64(0.15794943794779692)),
 (1379, np.float64(0.15794943794779692)),
 (4336, np.float64(0.1559625734730109)),
 (91, np.float64(0.1553424415003)),
 (168, np.float64(0.15404884978892902)),
 (3352, np.float64(0.1526406277181659)),
 (311, np.float64(0.1522038868295523)),
 (1961, np.float64(0.15110651212172094)),
 (577, np.float64(0.15007505629691606)),
 (3626, np.float64(0.15007505629691606)),
 (158, np.float64(0.1487044791289829)),
 (502, np.float64(0.1487044791289829)),
 (1176, np.float64(0.14763464883937316)),
 (1353, np.float64(0.14704292441876157)),
 (172, np.float64(0.14704292441876154)),
 (490, np.float64(0.14704292441876154)),
 (17, np.float64(0.1461508458653816)),
 (1934, np.float64(0.1454358496691159)),
 (111, np.float64(0.1453095484297741)),
 (2165, np.float64(0.1453095484297741)),
 (422, np.float64(0.14349920066683505)),
 (505, np.float64(0.14349920066683505)),
 (1484, np.float64(0.14349920066683505)),
 (41, np.float64(0.14237369936287486)),
 (84, np.float64(0.14165281524036175)),
 (369, np.float64(0.14097096860865022)),
 (557, np.float64(0.14097096860865022)),
 (568, np.float64(0.14097096860865022)),
 (2682, np.float64(0.14097096860865022)),
 (56, np.float64(0.14019992744655632)),
 (249, np.float64(0.14019992744655632)),
 (1325, np.float64(0.14019992744655632)),
 (2580, np.float64(0.14019992744655632)),
 (1320, np.float64(0.13949716649258315)),
 (332, np.float64(0.1389425035941821)),
 (1218, np.float64(0.1389425035941821)),
 (487, np.float64(0.1371182340382122)),
 (187, np.float64(0.13699915608779772)),
 (1669, np.float64(0.13678822577626598)),
 (2129, np.float64(0.13678822577626598)),
 (4348, np.float64(0.13678822577626598)),
 (2869, np.float64(0.13678822577626595)),
 (413, np.float64(0.13513513513513514)),
 (1941, np.float64(0.13513513513513514)),
 (2616, np.float64(0.1342312110428049)),
 (4490, np.float64(0.1342312110428049)),
 (342, np.float64(0.13377695860286035)),
 (595, np.float64(0.13334518676566626)),
 (1013, np.float64(0.13334518676566626)),
 (3407, np.float64(0.13334518676566626)),
 (3620, np.float64(0.13334518676566626)),
 (127, np.float64(0.13200500012082497)),
 (2476, np.float64(0.13181243254912406)),
 (1475, np.float64(0.1316245316231641)),
 (68, np.float64(0.13151918984428584)),
 (134, np.float64(0.13151918984428584)),
 (368, np.float64(0.13151918984428584)),
 (1156, np.float64(0.13151918984428584)),
 (2968, np.float64(0.13151918984428584)),
 (754, np.float64(0.12996881122750908)),
 (3671, np.float64(0.12996881122750908)),
 (1000, np.float64(0.12951986753290365)),
 (1045, np.float64(0.1289651760438322)),
 (1094, np.float64(0.1289651760438322)),
 (1654, np.float64(0.1289651760438322)),
 (2374, np.float64(0.1289651760438322)),
 (3374, np.float64(0.1289651760438322)),
 (3997, np.float64(0.1289651760438322)),
 (740, np.float64(0.1283740414907742)),
 (1613, np.float64(0.1283740414907742)),
 (1711, np.float64(0.12734290799340264)),
 (529, np.float64(0.12683657235796025)),
 (778, np.float64(0.12683657235796025)),
 (1035, np.float64(0.12683657235796025)),
 (483, np.float64(0.12655439943366653)),
 (420, np.float64(0.12535305264097507)),
 (1297, np.float64(0.12535305264097507)),
 (1737, np.float64(0.12527215359889848)),
 (939, np.float64(0.12427395320024)),
 (1743, np.float64(0.12427395320024)),
 (1829, np.float64(0.12427395320024)),
 (228, np.float64(0.12392039927415242)),
 (278, np.float64(0.12392039927415242)),
 (2709, np.float64(0.12392039927415242)),
 (3307, np.float64(0.12392039927415242)),
 (3405, np.float64(0.12392039927415242)),
 (1571, np.float64(0.12329924047901797)),
 (3216, np.float64(0.12329924047901797)),
 (2543, np.float64(0.12253577034896797)),
 (28, np.float64(0.1221125021745327)),
 (275, np.float64(0.1221125021745327)),
 (1272, np.float64(0.1221125021745327)),
 (2071, np.float64(0.1221125021745327)),
 (4673, np.float64(0.1221125021745327)),
 (454, np.float64(0.12119654139092992)),
 (549, np.float64(0.12119654139092992)),
 (95, np.float64(0.1211965413909299)),
 (432, np.float64(0.1211965413909299)),
 (238, np.float64(0.12050719759100866)),
 (72, np.float64(0.12006004503753284)),
 (579, np.float64(0.12006004503753284)),
 (1978, np.float64(0.12006004503753284)),
 (2864, np.float64(0.12006004503753284)),
 (1508, np.float64(0.11990028442779209)),
 (624, np.float64(0.11961783342433499)),
 (653, np.float64(0.11961783342433499)),
 (808, np.float64(0.11961783342433499)),
 (4201, np.float64(0.11961783342433499)),
 (3145, np.float64(0.11874787399915188)),
 (50, np.float64(0.11810771907149853)),
 (692, np.float64(0.1174278480752552)),
 (1275, np.float64(0.11742784807525519)),
 (3628, np.float64(0.11742784807525519)),
 (1570, np.float64(0.1162476387438193)),
 (123, np.float64(0.11624763874381927)),
 (166, np.float64(0.11624763874381927)),
 (169, np.float64(0.11624763874381927)),
 (232, np.float64(0.11624763874381927)),
 (294, np.float64(0.11624763874381927)),
 (687, np.float64(0.11624763874381927)),
 (859, np.float64(0.11624763874381927)),
 (1612, np.float64(0.11624763874381927)),
 (5, np.float64(0.11510231387903269)),
 (10, np.float64(0.1144727614064285)),
 (87, np.float64(0.1144727614064285)),
 (1029, np.float64(0.1144727614064285)),
 (2579, np.float64(0.1144727614064285)),
 (3006, np.float64(0.1144727614064285)),
 (199, np.float64(0.1139901881468883)),
 (81, np.float64(0.11389895949029986)),
 (627, np.float64(0.11314714296070713)),
 (1299, np.float64(0.11314714296070713)),
 (2255, np.float64(0.11314714296070713)),
 (2319, np.float64(0.11314714296070713)),
 (3719, np.float64(0.11314714296070713)),
 (3998, np.float64(0.11314714296070713)),
 (4016, np.float64(0.11314714296070713)),
 (126, np.float64(0.11277677488692017)),
 (508, np.float64(0.11277677488692017)),
 (777, np.float64(0.11185934253567072)),
 (14, np.float64(0.11115400287534567)),
 (854, np.float64(0.11115400287534567)),
 (900, np.float64(0.11115400287534567)),
 (1193, np.float64(0.11115400287534567)),
 (2009, np.float64(0.11115400287534567)),
 (2446, np.float64(0.11115400287534567)),
 (3496, np.float64(0.11115400287534567)),
 (1017, np.float64(0.11083777463036817)),
 (1369, np.float64(0.11028219331407116)),
 (1520, np.float64(0.11028219331407116)),
 (1717, np.float64(0.11028219331407116)),
 (1723, np.float64(0.11028219331407116)),
 (2630, np.float64(0.11028219331407116)),
 (3659, np.float64(0.11028219331407116)),
 (4133, np.float64(0.11028219331407116)),
 (18, np.float64(0.1098436937909367)),
 (1493, np.float64(0.1098436937909367)),
 (2102, np.float64(0.1098436937909367)),
 (2435, np.float64(0.1098436937909367)),
 (2756, np.float64(0.1098436937909367)),
 (513, np.float64(0.10959932487023819)),
 (1080, np.float64(0.10959932487023819)),
 (1292, np.float64(0.10959932487023819)),
 (3338, np.float64(0.10959932487023819)),
 (3618, np.float64(0.10959932487023819)),
 (4095, np.float64(0.10959932487023819)),
 (102, np.float64(0.10887588907733556)),
 (131, np.float64(0.10810810810810811)),
 (174, np.float64(0.10810810810810811)),
 (266, np.float64(0.10810810810810811)),
 (330, np.float64(0.10810810810810811)),
 (2068, np.float64(0.10810810810810811)),
 (3100, np.float64(0.10810810810810811)),
 (4077, np.float64(0.10810810810810811)),
 (403, np.float64(0.10793322294408637)),
 (141, np.float64(0.1076244005001263)),
 (3053, np.float64(0.1076244005001263)),
 (3779, np.float64(0.1076244005001263)),
 (3837, np.float64(0.1076244005001263)),
 (233, np.float64(0.10762440050012628)),
 (325, np.float64(0.10762440050012628)),
 (773, np.float64(0.10762440050012628)),
 (1154, np.float64(0.10762440050012628)),
 (3952, np.float64(0.10762440050012628)),
 (295, np.float64(0.106676149412533)),
 (312, np.float64(0.106676149412533)),
 (535, np.float64(0.106676149412533)),
 (2177, np.float64(0.106676149412533)),
 (4228, np.float64(0.106676149412533)),
 (182, np.float64(0.10529962529853128)),
 (986, np.float64(0.10529962529853128)),
 (139, np.float64(0.10524566699352861)),
 (4545, np.float64(0.10524566699352861)),
 (105, np.float64(0.10514994558491725)),
 (476, np.float64(0.10514994558491725)),
 (2452, np.float64(0.10514994558491725)),
 (2517, np.float64(0.10514994558491725)),
 (2558, np.float64(0.10514994558491725)),
 (2758, np.float64(0.10514994558491725)),
 (4196, np.float64(0.10514994558491725)),
 (4623, np.float64(0.10514994558491725)),
 (334, np.float64(0.10397504898200727)),
 (643, np.float64(0.10397504898200727)),
 (898, np.float64(0.10397504898200727)),
 (1054, np.float64(0.10397504898200727)),
 (3781, np.float64(0.10397504898200727)),
 (239, np.float64(0.10356162766686666)),
 (85, np.float64(0.10283867552865915)),
 (157, np.float64(0.10283867552865915)),
 (33, np.float64(0.10283867552865913)),
 (148, np.float64(0.10283867552865913)),
 (715, np.float64(0.10283867552865913)),
 (935, np.float64(0.10283867552865913)),
 (1278, np.float64(0.10283867552865913)),
 (1497, np.float64(0.10283867552865913)),
 (2656, np.float64(0.10283867552865913)),
 (4331, np.float64(0.10283867552865913)),
 (129, np.float64(0.10269923319261937)),
 (510, np.float64(0.10269923319261937)),
 (1107, np.float64(0.10269923319261937)),
 (3441, np.float64(0.10269923319261937)),
 (307, np.float64(0.1017387650221051)),
 (279, np.float64(0.10146925788636821)),
 (1084, np.float64(0.10146925788636821)),
 (1231, np.float64(0.10146925788636821)),
 (1271, np.float64(0.10146925788636821)),
 (2592, np.float64(0.10146925788636821)),
 (3462, np.float64(0.10146925788636821)),
 (4043, np.float64(0.10146925788636821)),
 (35, np.float64(0.10067340828210367)),
 (263, np.float64(0.10067340828210367)),
 (400, np.float64(0.10067340828210367)),
 (660, np.float64(0.10067340828210367)),
 (781, np.float64(0.10067340828210367)),
 (920, np.float64(0.10067340828210367)),
 (1304, np.float64(0.10067340828210367)),
 (1938, np.float64(0.10067340828210367)),
 (2657, np.float64(0.10067340828210367)),
 (4254, np.float64(0.10067340828210367)),
 (270, np.float64(0.10028244211278005)),
 (371, np.float64(0.10028244211278005)),
 (412, np.float64(0.10028244211278005)),
 (473, np.float64(0.10028244211278005)),
 (870, np.float64(0.10028244211278005)),
 (1200, np.float64(0.10028244211278005)),
 (1435, np.float64(0.10028244211278005)),
 (410, np.float64(0.09913631941932194)),
 (813, np.float64(0.09913631941932194)),
 (933, np.float64(0.09913631941932194)),
 (1274, np.float64(0.09913631941932194)),
 (1842, np.float64(0.09913631941932194)),
 (2280, np.float64(0.09913631941932194)),
 (292, np.float64(0.09863939238321438)),
 (389, np.float64(0.09863939238321438)),
 (530, np.float64(0.09863939238321438)),
 (691, np.float64(0.09863939238321438)),
 (791, np.float64(0.09863939238321438)),
 (1075, np.float64(0.09863939238321438)),
 (1404, np.float64(0.09863939238321438)),
 (2647, np.float64(0.09863939238321438)),
 (3734, np.float64(0.09863939238321438)),
 (1819, np.float64(0.09802861627917438)),
 (1999, np.float64(0.09802861627917438)),
 (1087, np.float64(0.09755285137982107)),
 (243, np.float64(0.09695723311274393)),
 (785, np.float64(0.09687303228651607)),
 (122, np.float64(0.09672388203287416)),
 (564, np.float64(0.09672388203287416)),
 (1470, np.float64(0.09672388203287416)),
 (1585, np.float64(0.09672388203287416)),
 (1682, np.float64(0.09672388203287416)),
 (1752, np.float64(0.09672388203287416)),
 (2648, np.float64(0.09672388203287416)),
 (3091, np.float64(0.09672388203287416)),
 (589, np.float64(0.09592022754223367)),
 (618, np.float64(0.09592022754223367)),
 (1355, np.float64(0.09592022754223367)),
 (43, np.float64(0.09491579957524991)),
 (2792, np.float64(0.09491579957524991)),
 (3152, np.float64(0.09491579957524991)),
 (12, np.float64(0.0949157995752499)),
 (23, np.float64(0.0949157995752499)),
 (142, np.float64(0.0949157995752499)),
 (236, np.float64(0.0949157995752499)),
 (362, np.float64(0.0949157995752499)),
 (1025, np.float64(0.0949157995752499)),
 (2089, np.float64(0.0949157995752499)),
 (2392, np.float64(0.0949157995752499)),
 (206, np.float64(0.09428928580058928)),
 (1414, np.float64(0.09394227846020416)),
 (160, np.float64(0.09367501681349609)),
 (511, np.float64(0.09320546490018)),
 (922, np.float64(0.09320546490018)),
 (1002, np.float64(0.09320546490018)),
 (2813, np.float64(0.09320546490018)),
 (2836, np.float64(0.09320546490018)),
 (3426, np.float64(0.09320546490018)),
 (596, np.float64(0.09299811099505542)),
 (1920, np.float64(0.09299811099505542)),
 (2484, np.float64(0.09299811099505542)),
 (479, np.float64(0.09248165577087424)),
 (1276, np.float64(0.09208185110322616)),
 (1828, np.float64(0.09208185110322616)),
 (164, np.float64(0.09158437663089954)),
 (21, np.float64(0.09158437663089952)),
 (242, np.float64(0.09158437663089952)),
 (306, np.float64(0.09158437663089952)),
 (794, np.float64(0.09158437663089952)),
 (960, np.float64(0.09158437663089952)),
 (978, np.float64(0.09158437663089952)),
 (1247, np.float64(0.09158437663089952)),
 (1519, np.float64(0.09158437663089952)),
 (4468, np.float64(0.09158437663089952)),
 (799, np.float64(0.09133277072519848)),
 (1492, np.float64(0.09119215051751065)),
 (2270, np.float64(0.09119215051751065)),
 (2384, np.float64(0.09119215051751065)),
 (2852, np.float64(0.09119215051751065)),
 (4353, np.float64(0.09119215051751065)),
 (4502, np.float64(0.09119215051751065)),
 (4516, np.float64(0.09119215051751065)),
 (4654, np.float64(0.09119215051751065)),
 (2444, np.float64(0.09077415526644964)),
 (2966, np.float64(0.09032775043542898)),
 (75, np.float64(0.09004503377814962)),
 (112, np.float64(0.09004503377814962)),
 (227, np.float64(0.09004503377814962)),
 (349, np.float64(0.09004503377814962)),
 (775, np.float64(0.09004503377814962)),
 (901, np.float64(0.09004503377814962)),
 (1374, np.float64(0.09004503377814962)),
 (1696, np.float64(0.09004503377814962)),
 (1786, np.float64(0.09004503377814962)),
 (2163, np.float64(0.09004503377814962)),
 (3447, np.float64(0.09004503377814962)),
 (3535, np.float64(0.09004503377814962)),
 (4626, np.float64(0.09004503377814962)),
 (170, np.float64(0.08948747402853657)),
 (812, np.float64(0.08948747402853657)),
 (2001, np.float64(0.08948747402853657)),
 (32, np.float64(0.08867021970429453)),
 (107, np.float64(0.08867021970429453)),
 (222, np.float64(0.08867021970429453)),
 (467, np.float64(0.08867021970429453)),
 (541, np.float64(0.08867021970429453)),
 (2494, np.float64(0.08867021970429453)),
 (1, np.float64(0.0885807893036239)),
 (88, np.float64(0.0885807893036239)),
 (121, np.float64(0.0885807893036239)),
 (245, np.float64(0.0885807893036239)),
 (315, np.float64(0.0885807893036239)),
 (786, np.float64(0.0885807893036239)),
 (894, np.float64(0.0885807893036239)),
 (3299, np.float64(0.0885807893036239)),
 (3814, np.float64(0.0885807893036239)),
 (45, np.float64(0.08787495503274936)),
 (230, np.float64(0.08787495503274936)),
 (363, np.float64(0.08787495503274936)),
 (381, np.float64(0.08787495503274936)),
 (1137, np.float64(0.08787495503274936)),
 (2876, np.float64(0.08787495503274936)),
 (4163, np.float64(0.08787495503274936)),
 (4737, np.float64(0.08787495503274936)),
 (2382, np.float64(0.0876249546540977)),
 (86, np.float64(0.08718572905786445)),
 (96, np.float64(0.08718572905786445)),
 (98, np.float64(0.08718572905786445)),
 (356, np.float64(0.08718572905786445)),
 (937, np.float64(0.08718572905786445)),
 (1111, np.float64(0.08718572905786445)),
 (1140, np.float64(0.08718572905786445)),
 (1267, np.float64(0.08718572905786445)),
 (2243, np.float64(0.08718572905786445)),
 (2247, np.float64(0.08718572905786445)),
 (2300, np.float64(0.08718572905786445)),
 (3089, np.float64(0.08718572905786445)),
 (4257, np.float64(0.08718572905786445)),
 (4657, np.float64(0.08718572905786445)),
 (654, np.float64(0.08710071126186844)),
 (1874, np.float64(0.08710071126186844)),
 (103, np.float64(0.0863465783552691)),
 (1280, np.float64(0.0863465783552691)),
 (39, np.float64(0.08585457105482137)),
 (101, np.float64(0.08585457105482137)),
 (203, np.float64(0.08585457105482137)),
 (457, np.float64(0.08585457105482137)),
 (547, np.float64(0.08585457105482137)),
 (814, np.float64(0.08585457105482137)),
 (899, np.float64(0.08585457105482137)),
 (1205, np.float64(0.08585457105482137)),
 (1469, np.float64(0.08585457105482137)),
 (2790, np.float64(0.08585457105482137)),
 (3308, np.float64(0.08585457105482137)),
 (193, np.float64(0.08561170049453902)),
 (501, np.float64(0.08561170049453902)),
 (1824, np.float64(0.08561170049453902)),
 (491, np.float64(0.08489527199560176)),
 (1401, np.float64(0.08489527199560176)),
 (2161, np.float64(0.08489527199560176)),
 (2246, np.float64(0.08489527199560176)),
 (3067, np.float64(0.08489527199560176)),
 (3439, np.float64(0.08489527199560176)),
 (4492, np.float64(0.08489527199560176)),
 (4718, np.float64(0.08489527199560176)),
 (257, np.float64(0.08458258116519013)),
 (626, np.float64(0.08458258116519013)),
 (746, np.float64(0.08458258116519013)),
 (787, np.float64(0.08458258116519013)),
 (3026, np.float64(0.08458258116519013)),
 (3138, np.float64(0.08458258116519013)),
 (3233, np.float64(0.08458258116519013)),
 (3421, np.float64(0.08458258116519013)),

In [118]:
def recommend(movie):
  index = movies[movies['title'] == movie].index[0]
  distance = sorted(list(enumerate(similarity[index])), reverse = True, key = lambda x:x[1])
  for i in distance[1:6]:
    print(movies.iloc[i[0]].title)

In [119]:
recommend('Superman')

Superman II
Superman Returns
Superman IV: The Quest for Peace
Superman III
Man of Steel

In [120]:
import pickle

In [121]:
pickle.dump(movies,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))